# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d87dfb981f695c8dae251533bdd0bfce21d272965b620c3090358939ff4726fd258873ec6257a10810da710d6bbd59a8bf093d006ca3ffc0b5d97372f0ba0a8

test:
  secret_key_base: 3bc907630ca7fd2a465f8c24ca97f006002df06d2082d787a8b95a4d49e24617d25a8ad7173481d3fc7f8a9c29ea6bdc4e7a142b32b12a20e1d399408b0fed28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
